# Generated by Django 3.0.5 on 2020-05-25 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fav_list',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lists.UserFlowersList'),
        ),
    ]
