# Generated by Django 3.0.5 on 2020-05-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200517_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_default.jpg', upload_to='profile_pics'),
        ),
    ]
