# Generated by Django 3.0.5 on 2020-05-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igarden', '0002_delete_userflowerslist'),
        ('users', '0003_auto_20200525_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fav_list',
        ),
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(related_name='favoured_by', to='igarden.Flower'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_default.jpg', upload_to='profile_pics'),
        ),
    ]
