# Generated by Django 3.0.5 on 2020-05-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20200517_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_default.jpg', upload_to='profile_pics'),
        ),
    ]
