# Generated by Django 3.0.5 on 2020-05-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igarden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flower',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
