# Generated by Django 3.0.5 on 2020-05-23 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igarden', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFlowersList',
        ),
    ]
