# Generated by Django 3.0.5 on 2020-05-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igarden', '0002_auto_20200517_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flower',
            old_name='photo',
            new_name='flower_photo',
        ),
    ]
