# Generated by Django 3.0.5 on 2020-05-17 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igarden', '0002_auto_20200517_2024'),
        ('igarden', '0003_auto_20200517_2027'),
    ]

    operations = [
    ]
