# Generated by Django 3.0.5 on 2020-05-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igarden', '0004_merge_20200517_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='flower_name',
        ),
        migrations.AddField(
            model_name='list',
            name='flower_names',
            field=models.ManyToManyField(to='igarden.Flower'),
        ),
    ]
