# Generated by Django 3.0.5 on 2020-05-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_favouriteslist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavouritesList',
        ),
    ]
